<?php
get_header();
$type = isset($_GET['type']) ? sanitize_title(wp_unslash($_GET['type'])) : '';
$features = isset($_GET['feature']) ? array_values(array_filter(array_map('sanitize_title', (array) wp_unslash($_GET['feature'])))) : [];
$materials = isset($_GET['material']) ? array_values(array_filter(array_map('sanitize_title', (array) wp_unslash($_GET['material'])))) : [];
$search = isset($_GET['q']) ? sanitize_text_field(wp_unslash($_GET['q'])) : '';
$tax_query = ['relation' => 'AND'];
if ($type) { $tax_query[] = ['taxonomy' => 'vasture_product_type', 'field' => 'slug', 'terms' => $type]; }
if ($features) { $tax_query[] = ['taxonomy' => 'vasture_product_feature', 'field' => 'slug', 'terms' => $features, 'operator' => 'AND']; }
if ($materials) { $tax_query[] = ['taxonomy' => 'vasture_product_material', 'field' => 'slug', 'terms' => $materials, 'operator' => 'AND']; }
$paged = max(1, (int) get_query_var('paged'));
$query = new WP_Query(['post_type' => 'vasture_product', 'post_status' => 'publish', 'posts_per_page' => 18, 'paged' => $paged, 's' => $search, 'tax_query' => count($tax_query) > 1 ? $tax_query : []]);
$type_terms = get_terms(['taxonomy' => 'vasture_product_type', 'hide_empty' => true]);
$feature_terms = get_terms(['taxonomy' => 'vasture_product_feature', 'hide_empty' => true]);
$material_terms = get_terms(['taxonomy' => 'vasture_product_material', 'hide_empty' => true]);
$selected = array_filter(array_merge($type ? [$type] : [], $features, $materials));
$is_en = vasture_is_en();
$pagination_args = ['total' => $query->max_num_pages, 'current' => $paged, 'type' => 'list', 'add_args' => array_filter(['type' => $type, 'feature' => $features, 'material' => $materials, 'q' => $search, 'lang' => $is_en ? 'en' : ''])];
?>
<section class="vasture-page-header"><div class="cf-container"><h1><?php echo $is_en ? 'Workwear & Functional Apparel<br/>Catalogue and Brand Manufacturing' : '工作服与功能性服装<br/>产品方案与品牌定制'; ?></h1><p><?php echo esc_html(vasture_t('从画册选款开始，按产品类别、核心功能和面料偏好筛选；每款产品可进一步提交供货、OEM或ODM询盘。', 'Start with the catalogue, then filter by product type, performance and fabric preference. Every product can be used for supply, OEM or ODM inquiries.')); ?></p></div></section>
<?php vasture_breadcrumbs(); ?>
<section class="cf-container vasture-catalogue-results"><div class="products-layout">
  <aside class="filter-sidebar"><div class="filter-card"><div class="filter-head"><div><span class="filter-kicker">PRODUCT FINDER</span><h3><?php echo esc_html(vasture_t('按需求选款', 'Find Products by Requirement')); ?></h3></div></div><p class="filter-guide"><?php echo esc_html(vasture_t('先选产品类别，再叠加功能或面料条件。', 'Choose a product type first, then add performance or fabric filters.')); ?></p>
  <form method="get" class="vasture-filter-form"><?php if ($is_en) : ?><input type="hidden" name="lang" value="en" /><?php endif; ?><div class="vasture-filter-search"><input type="search" name="q" value="<?php echo esc_attr($search); ?>" placeholder="<?php echo esc_attr(vasture_t('搜索型号、名称或功能', 'Search product ID, name or feature')); ?>" /><button type="submit"><?php echo esc_html(vasture_t('搜索', 'Search')); ?></button></div>
    <div class="filter-group"><div class="filter-group-title"><?php echo esc_html(vasture_t('产品类别', 'Product Type')); ?> <span><?php echo esc_html(vasture_t('单选', 'Single select')); ?></span></div><div class="filter-options"><label class="filter-option filter-option--all"><input type="radio" name="type" value="" <?php checked('', $type); ?> onchange="this.form.submit()"/><span class="filter-option__label"><?php echo esc_html(vasture_t('全部产品', 'All Products')); ?></span><span class="count"><?php echo esc_html(wp_count_posts('vasture_product')->publish); ?></span></label><?php foreach ($type_terms as $term) : ?><label class="filter-option"><input type="radio" name="type" value="<?php echo esc_attr($term->slug); ?>" <?php checked($term->slug, $type); ?> onchange="this.form.submit()"/><span class="filter-option__label"><?php echo esc_html(vasture_term_label($term)); ?></span><span class="count"><?php echo esc_html($term->count); ?></span></label><?php endforeach; ?></div></div>
    <div class="filter-group filter-group--chips"><div class="filter-group-title"><?php echo esc_html(vasture_t('核心功能', 'Key Features')); ?> <span><?php echo esc_html(vasture_t('可多选', 'Multiple select')); ?></span></div><div class="filter-options"><?php foreach ($feature_terms as $term) : ?><label class="filter-option"><input type="checkbox" name="feature[]" value="<?php echo esc_attr($term->slug); ?>" <?php checked(in_array($term->slug, $features, true)); ?> onchange="this.form.submit()"/><span class="filter-option__label"><?php echo esc_html(vasture_term_label($term)); ?></span><span class="count"><?php echo esc_html($term->count); ?></span></label><?php endforeach; ?></div></div>
    <div class="filter-group filter-group--chips"><div class="filter-group-title"><?php echo esc_html(vasture_t('面料偏好', 'Fabric Preference')); ?> <span><?php echo esc_html(vasture_t('可多选', 'Multiple select')); ?></span></div><div class="filter-options"><?php foreach ($material_terms as $term) : ?><label class="filter-option"><input type="checkbox" name="material[]" value="<?php echo esc_attr($term->slug); ?>" <?php checked(in_array($term->slug, $materials, true)); ?> onchange="this.form.submit()"/><span class="filter-option__label"><?php echo esc_html(vasture_term_label($term)); ?></span><span class="count"><?php echo esc_html($term->count); ?></span></label><?php endforeach; ?></div></div>
    <?php if ($selected || $search) : ?><p class="vasture-filter-active"><?php echo esc_html(vasture_t('已选条件', 'Active filters')); ?> · <a href="<?php echo esc_url(vasture_page_url('products')); ?>"><?php echo esc_html(vasture_t('清除', 'Clear')); ?></a></p><?php endif; ?>
  </form></div></aside>
  <div class="products-main"><div class="grid-toolbar vasture-results-toolbar" aria-live="polite"><div class="grid-toolbar__count"><span class="vasture-results-toolbar__eyebrow"><?php echo esc_html(vasture_t('产品目录', 'Catalogue Results')); ?></span><span><strong class="vasture-results-toolbar__number"><?php echo esc_html($query->found_posts); ?></strong> <span class="vasture-results-toolbar__label"><?php echo esc_html(vasture_t('款产品', 'products')); ?></span></span></div><div class="grid-toolbar__right"><span class="vasture-results-toolbar__hint"><?php echo esc_html(vasture_t('查看规格、颜色并提交询盘', 'View specifications, colours and inquire')); ?></span><?php if ($selected || $search) : ?><a class="vasture-results-toolbar__clear" href="<?php echo esc_url(vasture_page_url('products')); ?>"><?php echo esc_html(vasture_t('清除筛选', 'Clear filters')); ?></a><?php endif; ?></div></div><div class="product-grid">
  <?php if ($query->have_posts()) : while ($query->have_posts()) : $query->the_post(); $post_id = get_the_ID(); $variants = vasture_product_meta($post_id, 'color_variants', []); $card_badge = count($variants) > 1 ? count($variants) . ($is_en ? ' colours' : '色可选') : vasture_product_badge($post_id); ?>
    <article class="product-card reveal"><div class="product-card__img"><a class="product-card__link" href="<?php echo esc_url(vasture_lang_url(get_permalink($post_id))); ?>"><img src="<?php echo esc_url(vasture_product_image_url($post_id)); ?>" alt="<?php echo esc_attr(vasture_product_display_name($post_id)); ?>" loading="lazy" /></a><?php if ($card_badge !== '') : ?><span class="product-card__badge"><?php echo esc_html($card_badge); ?></span><?php endif; ?></div><div class="product-card__body"><span class="product-card__cat"><?php echo esc_html($is_en ? vasture_product_type_label($post_id) : vasture_product_meta($post_id, 'name_en')); ?></span><h2 class="product-card__title"><a href="<?php echo esc_url(vasture_lang_url(get_permalink($post_id))); ?>"><?php echo esc_html(vasture_product_display_name($post_id)); ?></a></h2><p class="product-card__desc"><?php echo esc_html($is_en ? vasture_product_summary($post_id) : get_the_excerpt()); ?></p><?php if ($variants) : ?><div class="vasture-product-card__colors" aria-label="<?php echo esc_attr($is_en ? count($variants) . ' colours' : count($variants) . '种颜色'); ?>"><?php foreach ($variants as $variant) : ?><i class="vasture-product-card__color"></i><?php endforeach; ?></div><?php endif; ?><div class="product-card__meta"><div class="product-card__moq"><?php echo esc_html(vasture_moq_label($post_id)); ?> <strong><?php echo esc_html(vasture_moq_value($post_id)); ?></strong></div><a href="<?php echo esc_url(add_query_arg('product', rawurlencode(vasture_product_meta($post_id, 'product_id')), vasture_page_url('contact'))); ?>" class="product-card__view"><?php echo esc_html(vasture_t('咨询', 'Inquire')); ?> <span aria-hidden="true">→</span></a></div></div></article>
  <?php endwhile; wp_reset_postdata(); else : ?><p><?php echo esc_html(vasture_t('没有符合当前条件的产品，请清除筛选后重试。', 'No products match these filters. Please clear the filters and try again.')); ?></p><?php endif; ?>
  </div><?php if ($query->max_num_pages > 1) : ?><div class="vasture-pagination-wrap"><nav class="vasture-pagination vasture-pagination--desktop" aria-label="<?php echo esc_attr(vasture_t('产品分页', 'Product pages')); ?>"><?php echo wp_kses_post(paginate_links(array_merge($pagination_args, ['mid_size' => 4, 'end_size' => 2]))); ?></nav><nav class="vasture-pagination vasture-pagination--mobile" aria-label="<?php echo esc_attr(vasture_t('产品分页', 'Product pages')); ?>"><?php echo wp_kses_post(paginate_links(array_merge($pagination_args, ['mid_size' => 1, 'end_size' => 1]))); ?></nav></div><?php endif; ?></div>
</div></section>
<?php get_footer();
