<?php
get_header();
while (have_posts()) : the_post();
$post_id = get_the_ID();
$variants = vasture_product_meta($post_id, 'color_variants', []);
$gallery = vasture_product_meta($post_id, 'gallery_ids', []);
$detail = vasture_product_meta($post_id, 'detail_ids', []);
$main_url = vasture_product_image_url($post_id, 'full');
$is_en = vasture_is_en();
$display_name = vasture_product_display_name($post_id);
$main_alt = $display_name;
?>
<article class="vasture-product"><div class="cf-container"><div class="vasture-product__layout"><div class="vasture-product__media"><img class="vasture-product__main-image" data-product-main src="<?php echo esc_url($main_url); ?>" alt="<?php echo esc_attr($main_alt); ?>" /><?php if ($variants) : ?><div class="vasture-product__thumbnails" aria-label="<?php echo esc_attr(vasture_t('颜色选择', 'Colour selection')); ?>"><?php foreach ($variants as $index => $variant) : $url = !empty($variant['attachment_id']) ? wp_get_attachment_image_url((int) $variant['attachment_id'], 'large') : ''; $variant_label = $is_en ? ($variant['label_en'] ?? $variant['label_zh'] ?? '') : ($variant['label_zh'] ?? ''); if (!$url) { continue; } ?><button class="vasture-product__thumbnail <?php echo $index === 0 ? 'is-active' : ''; ?>" type="button" data-product-image="<?php echo esc_url($url); ?>" data-product-alt="<?php echo esc_attr($variant_label); ?>"><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($variant_label); ?>" /></button><?php endforeach; ?></div><?php endif; ?></div>
<div class="vasture-product__info"><div class="vasture-product__type"><?php echo esc_html(vasture_product_type_label($post_id)); ?></div><h1><?php echo esc_html($display_name); ?></h1><div class="vasture-product__en"><?php echo esc_html($is_en ? get_the_title() : vasture_product_meta($post_id, 'name_en')); ?></div><p class="vasture-product__summary"><?php echo esc_html(vasture_product_summary($post_id)); ?></p><div class="vasture-product__facts"><div class="vasture-product__fact"><span><?php echo esc_html(vasture_t('供货方式', 'Supply Mode')); ?></span><strong><?php echo esc_html(vasture_supply_mode_label((string) vasture_product_meta($post_id, 'supply_mode'))); ?></strong></div><div class="vasture-product__fact"><span><?php echo esc_html(vasture_t('起订', 'Minimum Order')); ?></span><strong><?php echo esc_html($is_en ? vasture_moq_value($post_id) : vasture_moq_label($post_id) . ' ' . vasture_moq_value($post_id)); ?></strong></div></div>
<?php if ($variants) : ?><?php $first_label = $is_en ? ($variants[0]['label_en'] ?? $variants[0]['label_zh'] ?? '') : ($variants[0]['label_zh'] ?? ''); ?><p class="vasture-product__color-label"><?php echo esc_html(vasture_t('颜色选择：', 'Colour: ')); ?><strong data-product-colour-label><?php echo esc_html($first_label); ?></strong></p><div class="vasture-product__colour-options"><?php foreach ($variants as $index => $variant) : $url = !empty($variant['attachment_id']) ? wp_get_attachment_image_url((int) $variant['attachment_id'], 'thumbnail') : ''; $variant_label = $is_en ? ($variant['label_en'] ?? $variant['label_zh'] ?? '') : ($variant['label_zh'] ?? ''); if (!$url) { continue; } ?><button class="vasture-product__colour-option <?php echo $index === 0 ? 'is-active' : ''; ?>" type="button" data-product-image="<?php echo esc_url(wp_get_attachment_image_url((int) $variant['attachment_id'], 'large')); ?>" data-product-label="<?php echo esc_attr($variant_label); ?>"><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($variant_label); ?>" /></button><?php endforeach; ?></div><?php endif; ?>
<?php echo do_shortcode('[vasture_inquiry_form product_id="' . esc_attr(vasture_product_meta($post_id, 'product_id')) . '" lang="' . ($is_en ? 'en' : 'zh') . '"]'); ?></div></div>
<?php if ($gallery || $detail) : ?><section class="vasture-product__details"><h2><?php echo esc_html(vasture_t('产品细节参考', 'Product Details & References')); ?></h2><div class="vasture-product__detail-gallery"><?php foreach (array_unique(array_merge((array) $gallery, (array) $detail)) as $attachment_id) : $url = wp_get_attachment_image_url((int) $attachment_id, 'large'); if ($url) : ?><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($display_name . vasture_t('产品细节', ' product detail')); ?>" loading="lazy" /><?php endif; endforeach; ?></div></section><?php endif; ?>
</div></article>
<?php endwhile; get_footer();
