<?php
get_header();
while (have_posts()) : the_post();
$post_id = get_the_ID();
$variants = vasture_product_meta($post_id, 'color_variants', []);
$gallery = vasture_product_meta($post_id, 'gallery_ids', []);
$detail = vasture_product_meta($post_id, 'detail_ids', []);
$main_url = vasture_product_image_url($post_id, 'full');
$is_en = vasture_is_en();
$display_name = vasture_product_display_name($post_id);
$main_alt = $display_name;
?>
<article class="vasture-product"><div class="cf-container"><div class="vasture-product__layout"><div class="vasture-product__media"><img class="vasture-product__main-image" data-product-main src="<?php echo esc_url($main_url); ?>" alt="<?php echo esc_attr($main_alt); ?>" decoding="async" fetchpriority="high" /><?php if ($variants) : ?><div class="vasture-product__thumbnails" aria-label="<?php echo esc_attr(vasture_t('颜色选择', 'Colour selection')); ?>"><?php foreach ($variants as $index => $variant) : $url = !empty($variant['attachment_id']) ? wp_get_attachment_image_url((int) $variant['attachment_id'], 'large') : ''; $variant_label = $is_en ? ($variant['label_en'] ?? $variant['label_zh'] ?? '') : ($variant['label_zh'] ?? ''); if (!$url) { continue; } ?><button class="vasture-product__thumbnail <?php echo $index === 0 ? 'is-active' : ''; ?>" type="button" data-product-image="<?php echo esc_url($url); ?>" data-product-alt="<?php echo esc_attr($variant_label); ?>"><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($variant_label); ?>" loading="lazy" decoding="async" /></button><?php endforeach; ?></div><?php endif; ?></div>
<div class="vasture-product__info"><div class="vasture-product__type"><?php echo esc_html(vasture_product_type_label($post_id)); ?></div><h1><?php echo esc_html($display_name); ?></h1><div class="vasture-product__en"><?php echo esc_html($is_en ? get_the_title() : vasture_product_meta($post_id, 'name_en')); ?></div><p class="vasture-product__summary"><?php echo esc_html(vasture_product_summary($post_id)); ?></p><div class="vasture-product__facts"><div class="vasture-product__fact"><span><?php echo esc_html(vasture_t('供货方式', 'Supply Mode')); ?></span><strong><?php echo esc_html(vasture_supply_mode_label((string) vasture_product_meta($post_id, 'supply_mode'))); ?></strong></div><div class="vasture-product__fact"><span><?php echo esc_html(vasture_t('起订', 'Minimum Order')); ?></span><strong><?php echo esc_html($is_en ? vasture_moq_value($post_id) : vasture_moq_label($post_id) . ' ' . vasture_moq_value($post_id)); ?></strong></div></div>
<?php $is_high_vis_work_vest = has_term('vest', 'vasture_product_type', $post_id) && preg_match('/(hi-vis|high visibility|reflective|safety|高可视|反光|安全)/iu', $display_name . ' ' . (string) vasture_product_meta($post_id, 'name_en')) && !preg_match('/(dog|pet|宠物)/iu', $display_name . ' ' . (string) vasture_product_meta($post_id, 'name_en')); if ($is_high_vis_work_vest) : $certificate_is_mapped = vasture_product_has_certification($post_id, 'dk-ppe002779-i01'); ?><aside class="vasture-product__compliance <?php echo $certificate_is_mapped ? 'is-verified' : ''; ?>"><div><span class="vasture-product__compliance-eyebrow"><?php echo esc_html($certificate_is_mapped ? vasture_t('已关联认证文件', 'Mapped Compliance Document') : vasture_t('证书范围核验', 'Certificate Scope Check')); ?></span><strong><?php echo esc_html(vasture_t('高可视背心 CE 文件', 'Hi-Vis Vest CE Documentation')); ?></strong><p><?php echo esc_html($certificate_is_mapped ? vasture_t('此产品已在后台关联至证书 DK-PPE002779 i01。', 'This product is mapped to certificate DK-PPE002779 i01 in the catalogue backend.') : vasture_t('证书列明型号为 HW、LHVW100-Y、LHVW102-Y；下单前请按当前产品型号确认是否适用。', 'The certificate lists HW, LHVW100-Y and LHVW102-Y. Confirm applicability against the selected product ID before ordering.')); ?></p></div><div class="vasture-product__compliance-actions"><a href="<?php echo esc_url(vasture_page_url('certifications')); ?>"><?php echo esc_html(vasture_t('查看证书范围', 'View Certificate Scope')); ?> <span aria-hidden="true">→</span></a><a class="is-document" href="<?php echo esc_url(vasture_certification_file_url('dk-ppe002779-i01-eu-type-examination-certificate.pdf')); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html(vasture_t('查看证书', 'Open Certificate')); ?> <span aria-hidden="true">↗</span></a><a class="is-document" href="<?php echo esc_url(vasture_certification_file_url('dk-ppe002779-i01-annex.pdf')); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html(vasture_t('查看附件', 'Open Annex')); ?> <span aria-hidden="true">↗</span></a></div></aside><?php endif; ?>
<?php if ($variants) : ?><?php $first_label = $is_en ? ($variants[0]['label_en'] ?? $variants[0]['label_zh'] ?? '') : ($variants[0]['label_zh'] ?? ''); ?><p class="vasture-product__color-label"><?php echo esc_html(vasture_t('颜色选择：', 'Colour: ')); ?><strong data-product-colour-label><?php echo esc_html($first_label); ?></strong></p><div class="vasture-product__colour-options"><?php foreach ($variants as $index => $variant) : $url = !empty($variant['attachment_id']) ? wp_get_attachment_image_url((int) $variant['attachment_id'], 'thumbnail') : ''; $variant_label = $is_en ? ($variant['label_en'] ?? $variant['label_zh'] ?? '') : ($variant['label_zh'] ?? ''); if (!$url) { continue; } ?><button class="vasture-product__colour-option <?php echo $index === 0 ? 'is-active' : ''; ?>" type="button" data-product-image="<?php echo esc_url(wp_get_attachment_image_url((int) $variant['attachment_id'], 'large')); ?>" data-product-label="<?php echo esc_attr($variant_label); ?>"><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($variant_label); ?>" loading="lazy" decoding="async" /></button><?php endforeach; ?></div><?php endif; ?>
<?php echo do_shortcode('[vasture_inquiry_form product_id="' . esc_attr(vasture_product_meta($post_id, 'product_id')) . '" lang="' . ($is_en ? 'en' : 'zh') . '"]'); ?></div></div>
<?php if ($gallery || $detail) : ?><section class="vasture-product__details"><h2><?php echo esc_html(vasture_t('产品细节参考', 'Product Details & References')); ?></h2><div class="vasture-product__detail-gallery"><?php foreach (array_unique(array_merge((array) $gallery, (array) $detail)) as $attachment_id) : $url = wp_get_attachment_image_url((int) $attachment_id, 'large'); if ($url) : ?><img src="<?php echo esc_url($url); ?>" alt="<?php echo esc_attr($display_name . vasture_t('产品细节', ' product detail')); ?>" loading="lazy" decoding="async" /><?php endif; endforeach; ?></div></section><?php endif; ?>
</div></article>
<?php endwhile; get_footer();
